	<?php wp_footer(); ?>
	<footer>
        <ul class="footer">
          <li>&copy;</li>
          <li>
            <a
              href="https://github.com/Hania846"
              target="_blank"
              >Hania</a
            >
          </li>
          <li>
            <a
              href="https://github.com/charldll"
              target="_blank"
              >Inga</a
            >
          </li>
          <li>
            <a
              href="https://github.com/veelcheck"
              target="_blank"
              >Agnieszka</a
            >
          </li>
        </ul>
      </footer>
    </main>
  </body>
</html>